"""Output writers: Markdown (executive readable) and JSON (machine readable, eval input)."""

from __future__ import annotations

from pathlib import Path

from src.schemas import SummaryReport


def write_outputs(report: SummaryReport, base_path: Path, fmt: str) -> list[Path]:
    """Write the report to disk in the requested format(s). Returns paths written."""
    written: list[Path] = []
    base_path = base_path.with_suffix("")  # strip extension if user supplied one
    if fmt in ("md", "both"):
        md_path = base_path.with_suffix(".md")
        md_path.write_text(render_markdown(report), encoding="utf-8")
        written.append(md_path)
    if fmt in ("json", "both"):
        json_path = base_path.with_suffix(".json")
        json_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
        written.append(json_path)
    if not written:
        raise ValueError(f"unknown format {fmt!r}; expected md, json, or both")
    return written


def render_markdown(report: SummaryReport) -> str:
    md: list[str] = []
    md.append("# Portfolio Insight Report")
    md.append("")
    md.append(f"_Generated by `{report.metadata.model}` over {report.metadata.docs_processed} documents "
              f"in {report.metadata.duration_seconds:.1f}s. "
              f"Estimated cost ${report.metadata.estimated_cost_usd:.4f} "
              f"({report.metadata.total_tokens_input:,} input + {report.metadata.total_tokens_output:,} output tokens)._")
    md.append("")

    md.append("## Executive summary")
    md.append("")
    md.append(report.executive_summary.strip())
    md.append("")

    md.append("## Themes")
    md.append("")
    for t in report.findings.themes:
        md.append(f"### {t.name}  _(salience: {t.salience})_")
        md.append("")
        md.append(t.description.strip())
        md.append("")
        md.append(f"_Sources_: {_format_citations(t.citations)}")
        md.append("")

    md.append("## Key insights")
    md.append("")
    for i in report.findings.insights:
        conf = f" _(confidence: {i.confidence})_" if i.confidence else ""
        md.append(f"- {i.statement}{conf}  \n  _Sources_: {_format_citations(i.citations)}")
    md.append("")

    md.append("## Risks")
    md.append("")
    for r in report.findings.risks:
        md.append(f"- **{r.statement}**  _(likelihood: {r.likelihood} · impact: {r.impact})_  \n"
                  f"  _Sources_: {_format_citations(r.citations)}")
    md.append("")

    md.append("## Opportunities")
    md.append("")
    for o in report.findings.opportunities:
        md.append(f"- {o.statement}  \n  _Sources_: {_format_citations(o.citations)}")
    md.append("")

    md.append("## Recommended actions")
    md.append("")
    for a in report.findings.actions:
        meta_parts = []
        if a.owner:
            meta_parts.append(f"owner: {a.owner}")
        if a.timeframe:
            meta_parts.append(f"timeframe: {a.timeframe}")
        meta = f"  _({' · '.join(meta_parts)})_" if meta_parts else ""
        md.append(f"- {a.description}{meta}  \n  _Sources_: {_format_citations(a.citations)}")
    md.append("")

    md.append("## Assumptions")
    md.append("")
    for assumption in report.assumptions:
        md.append(f"- {assumption}")
    md.append("")

    md.append("## Limitations")
    md.append("")
    for lim in report.limitations:
        md.append(f"- {lim}")
    md.append("")

    md.append("---")
    md.append("")
    md.append(f"_Run timestamp: {report.metadata.timestamp_utc}_")
    md.append("")

    return "\n".join(md)


def _format_citations(citations: list[str]) -> str:
    return ", ".join(f"`{c}`" for c in citations)
